# Generated by Django 3.0.4 on 2020-03-29 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='branch_name', max_length=200)),
                ('display_name', models.CharField(default='Branch Name', max_length=200)),
                ('header_background_color', models.CharField(default='white', max_length=20)),
                ('header_text_color', models.CharField(default='black', max_length=20)),
                ('logo', models.ImageField(upload_to='logos')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture_location', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Branch')),
            ],
        ),
    ]
