# Generated by Django 3.0.4 on 2020-03-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='icon',
            field=models.ImageField(default=0, upload_to='icons'),
            preserve_default=False,
        ),
    ]
