# Generated by Django 3.0.4 on 2020-03-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_branch_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='background_color',
            field=models.CharField(default='white', max_length=20),
        ),
    ]
