# Generated by Django 3.0.4 on 2020-03-30 21:53

from django.db import migrations
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_branch_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='options',
            field=store.models.OptionsField(default=0),
            preserve_default=False,
        ),
    ]
