# Generated by Django 3.0.4 on 2020-04-19 19:48

from django.db import migrations
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='options',
            field=store.models.OptionsField(blank=True),
        ),
    ]
