# Generated by Django 3.0.4 on 2020-04-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200424_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='post',
            new_name='product',
        ),
        migrations.AddField(
            model_name='productimage',
            name='caption',
            field=models.CharField(default='', max_length=500),
        ),
    ]
