# Generated by Django 3.0.4 on 2020-04-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200424_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_main_image',
            field=models.BooleanField(default=False),
        ),
    ]
