# Generated by Django 3.0.4 on 2020-07-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productimage_is_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='other_branches',
            field=models.ManyToManyField(related_name='other_branch', to='store.Branch'),
        ),
    ]
